# Generated by Django 4.0.6 on 2022-07-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('1', 'BACKLOG'), ('2', 'TO DO'), ('3', 'DOING'), ('4', 'TEST'), ('5', 'DONE')], default='1', max_length=10)),
                ('priority', models.CharField(choices=[('1', 'ALTA'), ('2', 'MEDIA'), ('3', 'BAJA')], default='3', max_length=10)),
                ('date_of_delivery', models.DateTimeField()),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
